/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func([IDL.Float64, IDL.Text, IDL.Text], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };